'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("c2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_anchor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_anchor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_down_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_down_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_left_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_left_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_o_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_o_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_o_down_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_o_down_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_o_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_o_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_o_up_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_o_up_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_right_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_right_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_circle_up_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_circle_up_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_arrow_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_arrow_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_bullseye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_bullseye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_circle_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_circle_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_dot_circle_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_dot_circle_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_pause_circle_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_pause_circle_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_play_circle_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_play_circle_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_rotate_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_rotate_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_rotate_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_rotate_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_ship() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_ship", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_stop_circle_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_stop_circle_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_awesome_4_7_0_superpowers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_awesome_4_7_0_superpowers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
